-- SoftSin Studios board sanctions and server-side enforcement

create table if not exists public.board_sanctions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  sanction_type text not null check (sanction_type in ('warning', 'mute', 'suspension', 'ban')),
  reason_public text not null check (char_length(trim(reason_public)) between 3 and 500),
  note_private text not null default '' check (char_length(note_private) <= 2000),
  issued_by uuid not null references public.profiles(id) on delete restrict,
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  active boolean not null default true,
  acknowledged_at timestamptz,
  revoked_at timestamptz,
  revoked_by uuid references public.profiles(id) on delete restrict,
  revoke_reason text not null default '' check (char_length(revoke_reason) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint board_sanction_expiry check (expires_at is null or expires_at > starts_at)
);

create index if not exists board_sanctions_user_active_idx
  on public.board_sanctions (user_id, active, expires_at);
create index if not exists board_sanctions_created_idx
  on public.board_sanctions (created_at desc);

create table if not exists public.board_sanction_events (
  id bigint generated by default as identity primary key,
  sanction_id uuid not null references public.board_sanctions(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  event_type text not null check (event_type in ('issued', 'acknowledged', 'revoked', 'superseded')),
  note text not null default '' check (char_length(note) <= 2000),
  created_at timestamptz not null default now()
);

create index if not exists board_sanction_events_sanction_idx
  on public.board_sanction_events (sanction_id, created_at asc);

alter table public.board_sanctions enable row level security;
alter table public.board_sanction_events enable row level security;

drop policy if exists "Staff view sanctions" on public.board_sanctions;
create policy "Staff view sanctions"
on public.board_sanctions for select to authenticated
using (public.board_actor_is_staff(auth.uid()));

drop policy if exists "Staff view sanction events" on public.board_sanction_events;
create policy "Staff view sanction events"
on public.board_sanction_events for select to authenticated
using (public.board_actor_is_staff(auth.uid()));

revoke all on public.board_sanctions from anon, authenticated;
revoke all on public.board_sanction_events from anon, authenticated;
grant select on public.board_sanctions to authenticated;
grant select on public.board_sanction_events to authenticated;

create or replace function public.issue_board_sanction(
  target_user_id uuid,
  requested_type text,
  public_reason text,
  private_note text default '',
  duration_minutes integer default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  actor_role text;
  target_role text;
  new_id uuid;
  calculated_expiry timestamptz;
  superseded record;
begin
  select role into actor_role from public.profiles where id = actor_id;
  select role into target_role from public.profiles where id = target_user_id;

  if actor_role not in ('moderator', 'admin') then
    raise exception 'Moderator access is required.' using errcode = '42501';
  end if;
  if target_role is null then
    raise exception 'The selected member does not exist.';
  end if;
  if target_user_id = actor_id then
    raise exception 'You cannot sanction your own account.' using errcode = '42501';
  end if;
  if target_role = 'admin' then
    raise exception 'Administrator accounts are protected from board sanctions.' using errcode = '42501';
  end if;
  if actor_role = 'moderator' and target_role in ('moderator', 'admin') then
    raise exception 'Moderators cannot sanction staff accounts.' using errcode = '42501';
  end if;
  if requested_type not in ('warning', 'mute', 'suspension', 'ban') then
    raise exception 'Invalid sanction type.';
  end if;
  if char_length(trim(coalesce(public_reason, ''))) not between 3 and 500 then
    raise exception 'A public reason between 3 and 500 characters is required.';
  end if;
  if char_length(coalesce(private_note, '')) > 2000 then
    raise exception 'Private notes must be 2000 characters or less.';
  end if;

  if requested_type in ('mute', 'suspension') then
    if duration_minutes is null or duration_minutes < 5 or duration_minutes > 525600 then
      raise exception 'Timed restrictions require a duration from 5 minutes to 1 year.';
    end if;
    calculated_expiry := now() + make_interval(mins => duration_minutes);
  elsif requested_type = 'ban' and duration_minutes is not null then
    if duration_minutes < 5 or duration_minutes > 525600 then
      raise exception 'Timed bans require a duration from 5 minutes to 1 year.';
    end if;
    calculated_expiry := now() + make_interval(mins => duration_minutes);
  else
    calculated_expiry := null;
  end if;

  if requested_type in ('mute', 'suspension', 'ban') then
    for superseded in
      select id from public.board_sanctions
      where user_id = target_user_id
        and active = true
        and sanction_type in ('mute', 'suspension', 'ban')
        and (expires_at is null or expires_at > now())
      for update
    loop
      update public.board_sanctions
      set active = false,
          revoked_at = now(),
          revoked_by = actor_id,
          revoke_reason = 'Superseded by a new restriction.',
          updated_at = now()
      where id = superseded.id;

      insert into public.board_sanction_events (sanction_id, actor_id, event_type, note)
      values (superseded.id, actor_id, 'superseded', 'Superseded by a new restriction.');
    end loop;
  end if;

  insert into public.board_sanctions (
    user_id, sanction_type, reason_public, note_private, issued_by, expires_at
  ) values (
    target_user_id,
    requested_type,
    trim(public_reason),
    trim(coalesce(private_note, '')),
    actor_id,
    calculated_expiry
  ) returning id into new_id;

  insert into public.board_sanction_events (sanction_id, actor_id, event_type, note)
  values (new_id, actor_id, 'issued', trim(coalesce(private_note, '')));

  return new_id;
end;
$$;

create or replace function public.revoke_board_sanction(
  target_sanction_id uuid,
  revocation_reason text default 'Restriction lifted by staff.'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_id uuid := auth.uid();
  actor_role text;
  target_row public.board_sanctions%rowtype;
begin
  select role into actor_role from public.profiles where id = actor_id;
  if actor_role not in ('moderator', 'admin') then
    raise exception 'Moderator access is required.' using errcode = '42501';
  end if;

  select * into target_row from public.board_sanctions where id = target_sanction_id for update;
  if target_row.id is null then
    raise exception 'The selected sanction does not exist.';
  end if;
  if not target_row.active then
    return;
  end if;

  update public.board_sanctions
  set active = false,
      revoked_at = now(),
      revoked_by = actor_id,
      revoke_reason = left(trim(coalesce(revocation_reason, 'Restriction lifted by staff.')), 500),
      updated_at = now()
  where id = target_sanction_id;

  insert into public.board_sanction_events (sanction_id, actor_id, event_type, note)
  values (target_sanction_id, actor_id, 'revoked', left(trim(coalesce(revocation_reason, '')), 2000));
end;
$$;

create or replace function public.get_my_active_board_restriction()
returns table (
  sanction_type text,
  reason_public text,
  starts_at timestamptz,
  expires_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select s.sanction_type, s.reason_public, s.starts_at, s.expires_at
  from public.board_sanctions s
  where s.user_id = auth.uid()
    and s.active = true
    and s.sanction_type in ('mute', 'suspension', 'ban')
    and (s.expires_at is null or s.expires_at > now())
  order by
    case s.sanction_type when 'ban' then 1 when 'suspension' then 2 else 3 end,
    s.created_at desc
  limit 1;
$$;

create or replace function public.get_my_active_board_warning()
returns table (
  id uuid,
  reason_public text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select s.id, s.reason_public, s.created_at
  from public.board_sanctions s
  where s.user_id = auth.uid()
    and s.active = true
    and s.sanction_type = 'warning'
    and s.acknowledged_at is null
  order by s.created_at asc
  limit 1;
$$;

create or replace function public.acknowledge_board_warning(target_sanction_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  warning_row public.board_sanctions%rowtype;
begin
  select * into warning_row
  from public.board_sanctions
  where id = target_sanction_id
    and user_id = auth.uid()
    and sanction_type = 'warning'
  for update;

  if warning_row.id is null then
    raise exception 'The selected warning is unavailable.' using errcode = '42501';
  end if;
  if warning_row.acknowledged_at is not null then
    return;
  end if;

  update public.board_sanctions
  set active = false,
      acknowledged_at = now(),
      updated_at = now()
  where id = target_sanction_id;

  insert into public.board_sanction_events (sanction_id, actor_id, event_type, note)
  values (target_sanction_id, auth.uid(), 'acknowledged', 'Warning acknowledged by member.');
end;
$$;

create or replace function public.enforce_board_sanction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  restriction record;
begin
  select * into restriction from public.get_my_active_board_restriction();

  if restriction.sanction_type is not null then
    if restriction.expires_at is null then
      raise exception 'Your board account is restricted: %. Reason: %', restriction.sanction_type, restriction.reason_public
        using errcode = '42501';
    else
      raise exception 'Your board account is restricted until %. Reason: %', restriction.expires_at, restriction.reason_public
        using errcode = '42501';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_thread_sanction on public.threads;
create trigger enforce_thread_sanction
before insert or update on public.threads
for each row execute function public.enforce_board_sanction();

drop trigger if exists enforce_post_sanction on public.posts;
create trigger enforce_post_sanction
before insert or update on public.posts
for each row execute function public.enforce_board_sanction();

revoke all on function public.issue_board_sanction(uuid, text, text, text, integer) from public;
revoke all on function public.revoke_board_sanction(uuid, text) from public;
revoke all on function public.get_my_active_board_restriction() from public;
revoke all on function public.get_my_active_board_warning() from public;
revoke all on function public.acknowledge_board_warning(uuid) from public;
grant execute on function public.issue_board_sanction(uuid, text, text, text, integer) to authenticated;
grant execute on function public.revoke_board_sanction(uuid, text) to authenticated;
grant execute on function public.get_my_active_board_restriction() to authenticated;
grant execute on function public.get_my_active_board_warning() to authenticated;
grant execute on function public.acknowledge_board_warning(uuid) to authenticated;
