-- SoftSin Studios board reporting and moderation queue

create extension if not exists pgcrypto;

create table if not exists public.board_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  thread_id uuid references public.threads(id) on delete set null,
  post_id uuid references public.posts(id) on delete set null,
  reason text not null check (reason in ('spam', 'harassment', 'illegal', 'impersonation', 'misinformation', 'off-topic', 'other')),
  details text not null default '' check (char_length(details) <= 2000),
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  reviewed_by uuid references public.profiles(id) on delete set null,
  resolution_note text not null default '' check (char_length(resolution_note) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint board_reports_one_target check (
    (thread_id is not null and post_id is null)
    or (thread_id is null and post_id is not null)
  )
);

create index if not exists board_reports_status_created_idx
  on public.board_reports (status, created_at desc);
create index if not exists board_reports_reporter_idx
  on public.board_reports (reporter_id, created_at desc);
create index if not exists board_reports_thread_idx
  on public.board_reports (thread_id) where thread_id is not null;
create index if not exists board_reports_post_idx
  on public.board_reports (post_id) where post_id is not null;

create table if not exists public.board_report_events (
  id bigint generated by default as identity primary key,
  report_id uuid not null references public.board_reports(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete restrict,
  from_status text,
  to_status text not null,
  note text not null default '' check (char_length(note) <= 2000),
  created_at timestamptz not null default now()
);

create index if not exists board_report_events_report_idx
  on public.board_report_events (report_id, created_at asc);

create or replace function public.board_actor_is_staff(actor uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = actor and role in ('moderator', 'admin')
  );
$$;

create or replace function public.validate_board_report()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_author uuid;
begin
  if auth.uid() is null or new.reporter_id <> auth.uid() then
    raise exception 'A valid member session is required.' using errcode = '42501';
  end if;

  new.details := trim(coalesce(new.details, ''));
  new.status := 'open';
  new.reviewed_by := null;
  new.resolution_note := '';
  new.resolved_at := null;

  if new.thread_id is not null then
    select author_id into target_author
    from public.threads
    where id = new.thread_id and deleted_at is null;
  else
    select author_id into target_author
    from public.posts
    where id = new.post_id and deleted_at is null;
  end if;

  if target_author is null then
    raise exception 'The reported content no longer exists.';
  end if;

  if target_author = auth.uid() then
    raise exception 'You cannot report your own content.';
  end if;

  if exists (
    select 1 from public.board_reports r
    where r.reporter_id = auth.uid()
      and r.status in ('open', 'reviewing')
      and r.thread_id is not distinct from new.thread_id
      and r.post_id is not distinct from new.post_id
  ) then
    raise exception 'You already have an active report for this content.';
  end if;

  return new;
end;
$$;

create or replace function public.update_board_report()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.board_actor_is_staff(auth.uid()) then
    raise exception 'Moderator access is required.' using errcode = '42501';
  end if;

  new.reporter_id := old.reporter_id;
  new.thread_id := old.thread_id;
  new.post_id := old.post_id;
  new.reason := old.reason;
  new.details := old.details;
  new.created_at := old.created_at;
  new.updated_at := now();
  new.reviewed_by := auth.uid();

  if new.status in ('resolved', 'dismissed') then
    new.resolved_at := coalesce(old.resolved_at, now());
  else
    new.resolved_at := null;
  end if;

  return new;
end;
$$;

create or replace function public.log_board_report_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.board_report_events (report_id, actor_id, from_status, to_status, note)
    values (new.id, new.reporter_id, null, new.status, new.details);
  elsif new.status is distinct from old.status
     or new.resolution_note is distinct from old.resolution_note then
    insert into public.board_report_events (report_id, actor_id, from_status, to_status, note)
    values (new.id, auth.uid(), old.status, new.status, new.resolution_note);
  end if;

  return new;
end;
$$;

drop trigger if exists validate_board_report_insert on public.board_reports;
create trigger validate_board_report_insert
before insert on public.board_reports
for each row execute function public.validate_board_report();

drop trigger if exists validate_board_report_update on public.board_reports;
create trigger validate_board_report_update
before update on public.board_reports
for each row execute function public.update_board_report();

drop trigger if exists log_board_report_event on public.board_reports;
create trigger log_board_report_event
after insert or update on public.board_reports
for each row execute function public.log_board_report_event();

alter table public.board_reports enable row level security;
alter table public.board_report_events enable row level security;

drop policy if exists "Members create their own reports" on public.board_reports;
create policy "Members create their own reports"
on public.board_reports for insert to authenticated
with check (reporter_id = auth.uid());

drop policy if exists "Members view their own reports" on public.board_reports;
create policy "Members view their own reports"
on public.board_reports for select to authenticated
using (reporter_id = auth.uid() or public.board_actor_is_staff(auth.uid()));

drop policy if exists "Staff update reports" on public.board_reports;
create policy "Staff update reports"
on public.board_reports for update to authenticated
using (public.board_actor_is_staff(auth.uid()))
with check (public.board_actor_is_staff(auth.uid()));

drop policy if exists "Staff view report history" on public.board_report_events;
create policy "Staff view report history"
on public.board_report_events for select to authenticated
using (public.board_actor_is_staff(auth.uid()));

revoke all on public.board_reports from anon;
revoke all on public.board_report_events from anon;
grant select, insert on public.board_reports to authenticated;
grant update (status, resolution_note) on public.board_reports to authenticated;
grant select on public.board_report_events to authenticated;
grant execute on function public.board_actor_is_staff(uuid) to authenticated;
